#!/usr/bin/env bash

# For shellcheck
export status=0

# Happens before every bat file
_common_setup()
{
   # This setup script would be called from the git test directory
   load '../node_modules/bats-support/load.bash'
   load '../node_modules/bats-assert/load.bash'
   # get the containing directory of this file
   # use $BATS_TEST_FILENAME instead of ${BASH_SOURCE[0]} or $0,
   # as those will point to the bats executable's location or the preprocessed file respectively
   PROJECT_ROOT="$( cd "$( dirname "$BATS_TEST_FILENAME" )/.." >/dev/null 2>&1 && pwd )"
   # make executables in src/ visible to PATH
   PATH="$PROJECT_ROOT/src:$PATH"

   cd "$PROJECT_ROOT/test" || exit

}

