"RailThickness"= 3.175mm
"StepperHoleDiameter"= 24mm'Spec
"StepperMountingHoleDiameter"= 3.175mm
"SideRailLength"= 550mm
"StepperMountingHoleDistance"= 31mm
"VerticalSupportWidth"= 1.75in
"StepperMountingHoleOffsetFromLeftOrRightSide"= "StepperMountingHoleOffsetFromItsSide" + "RailThickness"
"HoleOffsetFromEdge"= "RailThickness" * 2.5
"HoleOffsetFromSide"= "RailThickness" * 3.5
"StepperWidth"= 42mm
"StepperMountingHoleOffsetFromItsSide"= 5.5mm
"FasteningHoleDiameter"= .125in
"FrontBackRailLength"= 530mm
"DistanceBetweenFrontToBackStepperHoles"= "BedLength" - "BedStepperFrameDiameter"
"DistanceBetweenLeftToRightStepperHoles"= "FrontBackRailLength" - "StepperMountingHoleOffsetFromLeftOrRightSide" * 2 - "StepperHoleDiameter"
"BedThickness"= 20mm
"ThreadedNutMountHoleDistanceFromCenter"= 8mm
"BedSpringHolesXDistanceFromSide"= 7mm
"BedSpringHolesYDistanceFromSide"= 41mm
"BedSquareWidth"= "BuildPlateWidth" + "BedIncresedByLength"
"BedSpringHoleXOffsetFromBedSide"= ( "BedSquareWidth" - 350 ) / 2 + "BedSpringHolesXDistanceFromSide"
"BedSpringHoleSize"= 3mm
"BedSringHoleYHoleOffsetFromBedFront"= ( "BedSquareWidth" - 350 ) / 2 + "BedSpringHolesYDistanceFromSide"
"BedLLongSide"= "BedThirdSize" * 3 + "BedIncreasedByWidth" / 2
"BedLShortSide"= "BedThirdSize" * 2 + "BedIncreasedByWidth" / 2
"BedLWidth"= "BedThirdSize" + "BedOverlap" + "BedIncreasedByWidth" / 2
"D4@CornerrSketch1"="BedLWidth"
"D1@CornerrSketch1"="BedLLongSide"
"BedInnerSquareWidth"= "BedThirdSize" * 3
"BedOuterSquareSize"= "BuildPlateWidth" + "BedIncreasedByWidth"
"BuildPlateWidth"= 350mm'Spec
"BuildPlateLength"= 350mm'Spec
"BedInnerSquareLength"= "BedInnerSquareWidth"
"BedOverlap"= 20mm
"BedWidth"= "BedInnerSquareWidth" + "BedLWidth" * 2 - "BedOverlap" * 2
"BedIncreasedByWidth"= 20mm
"BedIncresedByLength"= 20mm
"BedWidthCalculationCheck"= "BuildPlateWidth" + "BedIncreasedByWidth"'Should Equal BedWidth
"BedThirdSize"= 70mm
"BedLengthCalculationCheck1"= "BuildPlateLength" + "BedIncresedByLength"'Should Equal BedLength
"BedLengthCalculationCheck2"= "BedLLongSide" + "BedLShortSide"'Should Equal BedLength
"BedLength"= "BedInnerSquareLength" + "BedLWidth" * 2 - "BedOverlap" * 2
"D2@InnerCutSketch1"="BedOverlap"
"D1@Tab holes-Sketch1" = "BedOverlap" / 2
"D2@Tab holes-Sketch1" = "BedOverlap" / 2
"D4@Tab holes-Sketch1"="BedOverlap"
"D6@Tab holes-Sketch1"="BedOverlap"
"D3@Tab holes-Sketch1"=55mm
"BedSquareLength"= "BuildPlateLength" + "BedIncresedByLength"
"D1@TRPegCapSketch2" = "BedThickness" / 2 + "StandardWallThickness" * 2
"StandardWallThickness"= 5mm
"D2@TRPegCapSketch2" = "StandardWallThickness"
"D3@TRPegCapSketch2"="BedThickness" - "StandardWallThickness"
"D1@TRPegCapBoss-Extrude2" = "StandardWallThickness"
"D1@BottomPegHoleCut-Extrude1"="StandardWallThickness"
"D1@Shell2"="StandardWallThickness"
"D2@TRPegSketch1"="BedThickness"-"StandardWallThickness"*2
"D5@CornerrSketch1"="DistanceFromBedSideToStepperHole"
"D2@CornerrSketch1"="StepperHoleDiameter" +10mm
"BedStepperFrameDiameter"= "StepperHoleDiameter" + 10mm
"DistanceFromBedSideToStepperHole"= ( "FrontBackRailLength" - "BedWidth" - "StepperMountingHoleOffsetFromLeftOrRightSide" * 2 - "StepperHoleDiameter" ) / 2
"D7@CornerrSketch1"="BedLShortSide"
